from __future__ import annotations

from enum import StrEnum

class ErrorCode(StrEnum):
    AUTOMATION_ERROR_CODE = "FALHA_NA_AUTOMACAO"
    BROWSER_SESSION_OPEN_ERROR_CODE = "SESSAO_JA_ABERTA"
    BROWSER_SESSION_CLOSED_ERROR_CODE = "SESSAO_FECHADA"
    PAYMENT_CONFIRMATION_DISABLED_ERROR_CODE = "CONFIRMACAO_PAGAMENTO_DESABILITADA"
    EXTERNAL_SERVICE_ERROR_CODE = "SERVICO_EXTERNO_INDISPONIVEL"