from __future__ import annotations

from enum import Enum


class ErrorCode(Enum):
    BAD_REQUEST = "REQUISICAO_INVALIDA"
    NOT_FOUND = "ROTA_NAO_ENCONTRADA"
    METHOD_NOT_ALLOWED = "METODO_NAO_PERMITIDO"
    INTERNAL_SERVER_ERROR = "ERRO_INTERNO"
    AUTOMATION_ERROR_CODE = "FALHA_NA_AUTOMACAO"
    BROWSER_SESSION_OPEN_ERROR_CODE = "SESSAO_JA_ABERTA"
    BROWSER_SESSION_CLOSED_ERROR_CODE = "SESSAO_FECHADA"
    PAGE_REDIRECTION_ERROR_CODE = "ERRO_NO_REDIRECIONAMENTO_DA_PAGINA"
    PAYMENT_CONFIRMATION_DISABLED_ERROR_CODE = "CONFIRMACAO_PAGAMENTO_DESABILITADA"
    EXTERNAL_SERVICE_ERROR_CODE = "SERVICO_EXTERNO_INDISPONIVEL"
    INVALID_CPF_ERROR_CODE = "CPF_INVALIDO"
    INVALID_PASSWORD_ERROR_CODE = "SENHA_INVALIDA"
    INDIVIDUAL_BET_REGISTRATION_CLOSED_ERROR_CODE = "REGISTRO_APOSTA_INDIVIDUAL_FECHADO"
    BET_TEMPORARILY_DISABLED_ERROR_CODE = "APOSTA_TEMPORARIAMENTE_DESABILITADA"
    DAILY_PURCHASE_LIMIT_ERROR_CODE = "LIMITE_MAXIMO_DIARIO_DE_COMPRAS"
    BETS_NOT_AVAILABLE_FOR_CAPTURE_ERROR_CODE = "APOSTAS_NAO_DISPONIVEIS_PARA_CAPTACAO"
