from __future__ import annotations

from enum import StrEnum

class ErrorCode(StrEnum):
    BAD_REQUEST = "REQUISICAO_INVALIDA"
    NOT_FOUND = "ROTA_NAO_ENCONTRADA"
    METHOD_NOT_ALLOWED = "METODO_NAO_PERMITIDO"
    INTERNAL_SERVER_ERROR = "ERRO_INTERNO"
    AUTOMATION_ERROR_CODE = "FALHA_NA_AUTOMACAO"
    BROWSER_SESSION_OPEN_ERROR_CODE = "SESSAO_JA_ABERTA"
    BROWSER_SESSION_CLOSED_ERROR_CODE = "SESSAO_FECHADA"
    PAYMENT_CONFIRMATION_DISABLED_ERROR_CODE = "CONFIRMACAO_PAGAMENTO_DESABILITADA"
    EXTERNAL_SERVICE_ERROR_CODE = "SERVICO_EXTERNO_INDISPONIVEL",
    INVALID_CPF_ERROR_CODE = "CPF_INVALIDO",
    INVALID_PASSWORD_ERROR_CODE = "SENHA_INVALIDA",
    INDIVIDUAL_BET_REGISTRATION_CLOSED_ERROR_CODE = "REGISTRO_APOSTA_INDIVIDUAL_FECHADO",