from enum import Enum


class WhatsAppSessionStatus(Enum):
    SESSION_CLOSED = "SESSAO_FECHADA"
    STARTING_SESSION = "INICIANDO_SESSAO"
    WAITING_FOR_AUTHENTICATION = "AGUARDANDO_AUTENTICACAO"
    LOADING_CONVERSATIONS = "CARREGANDO_CONVERSAS"
    SESSION_OPEN = "SESSAO_ABERTA"
