from domain.constants.error_messages import (
    FALLBACK_EMAIL_SEND_FAILED,
    VALIDATION_CODE_FETCH_TIMEOUT,
    VALIDATION_CODE_FETCH_FAILED,
    GMAIL_READER_API_VALIDATION_CODE_NOT_RETURNED,
    BROWSER_SESSION_OPEN,
    BROWSER_SESSION_CLOSED,
    INVALID_CPF,
    INVALID_PASSWORD,
)

__all__ = [
    "FALLBACK_EMAIL_SEND_FAILED", 
    "VALIDATION_CODE_FETCH_TIMEOUT",
    "VALIDATION_CODE_FETCH_FAILED",
    "GMAIL_READER_API_VALIDATION_CODE_NOT_RETURNED",
    "BROWSER_SESSION_OPEN",
    "BROWSER_SESSION_CLOSED",
    "INVALID_CPF", 
    "INVALID_PASSWORD"
]
