from application.notification.notification_message_builder import NotificationMessageBuilder
from application.notification.error_message_builder import ErrorMessageBuilder

build_email_message = NotificationMessageBuilder.build_email_message
build_whatsapp_message = NotificationMessageBuilder.build_whatsapp_message
get_error_message = ErrorMessageBuilder.get_error_message

__all__ = ["build_email_message", "build_whatsapp_message", "get_error_message"]
